# Generated by Django 5.2.7 on 2025-10-31 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_l', models.PositiveIntegerField(default=100)),
                ('min_level_l', models.PositiveIntegerField(default=30)),
                ('max_level_l', models.PositiveIntegerField(default=90)),
                ('temp_set_c', models.FloatField(default=35.0)),
                ('temp_min_c', models.FloatField(default=25.0)),
                ('temp_max_c', models.FloatField(default=45.0)),
                ('hysteresis_c', models.FloatField(default=2.0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del tanque',
                'verbose_name_plural': 'Configuraciones de tanque',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('VALVE_OPEN', 'Válvula abierta'), ('VALVE_CLOSE', 'Válvula cerrada'), ('HEATER_ON', 'Resistencia encendida'), ('HEATER_OFF', 'Resistencia apagada'), ('HEATER_SAFE_OFF', 'Resistencia apagada por seguridad'), ('SAFE_MODE', 'Modo seguro activado')], max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts'], name='control_eve_ts_05cec7_idx'), models.Index(fields=['code'], name='control_eve_code_fc7342_idx')],
            },
        ),
        migrations.CreateModel(
            name='TankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_l', models.FloatField()),
                ('temp_c', models.FloatField()),
                ('valve_open', models.BooleanField(default=False)),
                ('heater_on', models.BooleanField(default=False)),
                ('safe_mode', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='control.tankconfig')),
            ],
            options={
                'verbose_name': 'Estado del tanque',
                'verbose_name_plural': 'Estados del tanque',
                'ordering': ['-ts'],
            },
        ),
    ]
