# Generated by Django 5.2.7 on 2025-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankstate',
            name='drain_valve_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='code',
            field=models.CharField(choices=[('VALVE_OPEN', 'Válvula abierta'), ('VALVE_CLOSE', 'Válvula cerrada'), ('HEATER_ON', 'Resistencia encendida'), ('HEATER_OFF', 'Resistencia apagada'), ('HEATER_SAFE_OFF', 'Resistencia apagada por seguridad'), ('SAFE_MODE', 'Modo seguro activado'), ('DRAIN_OPEN', 'Válvula de vaciado abierta'), ('DRAIN_CLOSE', 'Válvula de vaciado cerrada')], max_length=32),
        ),
    ]
