# Generated by Django 5.2.7 on 2025-10-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_tankstate_drain_valve_open_alter_eventlog_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankconfig',
            name='control_mode',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='tankconfig',
            name='manual_drain_valve_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tankconfig',
            name='manual_heater_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tankconfig',
            name='manual_valve_open',
            field=models.BooleanField(default=False),
        ),
    ]
