# Generated by Django 5.2.7 on 2025-10-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_tankconfig_control_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankconfig',
            name='manual_heater_150_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tankconfig',
            name='manual_heater_500_on',
            field=models.BooleanField(default=False),
        ),
    ]
